/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) UR5_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {19, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {59, 1, 1};
static const casadi_int casadi_s3[3] = {31, 1, 1};

/* UR5_expl_vde_adj:(i0[19],i1[19],i2[12],i3[59])->(o0[31]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  if (res[0]!=0) res[0][3]=a00;
  if (res[0]!=0) res[0][4]=a00;
  if (res[0]!=0) res[0][5]=a00;
  a01=arg[0]? arg[0][12] : 0;
  a02=arg[1]? arg[1][0] : 0;
  a03=(a01*a02);
  if (res[0]!=0) res[0][6]=a03;
  a03=arg[1]? arg[1][1] : 0;
  a04=(a01*a03);
  if (res[0]!=0) res[0][7]=a04;
  a04=arg[1]? arg[1][2] : 0;
  a05=(a01*a04);
  if (res[0]!=0) res[0][8]=a05;
  a05=arg[1]? arg[1][3] : 0;
  a06=(a01*a05);
  if (res[0]!=0) res[0][9]=a06;
  a06=arg[1]? arg[1][4] : 0;
  a07=(a01*a06);
  if (res[0]!=0) res[0][10]=a07;
  a07=arg[1]? arg[1][5] : 0;
  a08=(a01*a07);
  if (res[0]!=0) res[0][11]=a08;
  a08=arg[2]? arg[2][5] : 0;
  a09=arg[1]? arg[1][11] : 0;
  a08=(a08*a09);
  a10=arg[2]? arg[2][4] : 0;
  a11=arg[1]? arg[1][10] : 0;
  a10=(a10*a11);
  a08=(a08+a10);
  a10=arg[2]? arg[2][3] : 0;
  a12=arg[1]? arg[1][9] : 0;
  a10=(a10*a12);
  a08=(a08+a10);
  a10=arg[2]? arg[2][2] : 0;
  a13=arg[1]? arg[1][8] : 0;
  a10=(a10*a13);
  a08=(a08+a10);
  a10=arg[2]? arg[2][1] : 0;
  a14=arg[1]? arg[1][7] : 0;
  a10=(a10*a14);
  a08=(a08+a10);
  a10=arg[2]? arg[2][0] : 0;
  a15=arg[1]? arg[1][6] : 0;
  a10=(a10*a15);
  a08=(a08+a10);
  a10=arg[0]? arg[0][11] : 0;
  a10=(a10*a07);
  a08=(a08+a10);
  a10=arg[0]? arg[0][10] : 0;
  a10=(a10*a06);
  a08=(a08+a10);
  a10=arg[0]? arg[0][9] : 0;
  a10=(a10*a05);
  a08=(a08+a10);
  a10=arg[0]? arg[0][8] : 0;
  a10=(a10*a04);
  a08=(a08+a10);
  a10=arg[0]? arg[0][7] : 0;
  a10=(a10*a03);
  a08=(a08+a10);
  a10=arg[0]? arg[0][6] : 0;
  a10=(a10*a02);
  a08=(a08+a10);
  if (res[0]!=0) res[0][12]=a08;
  if (res[0]!=0) res[0][13]=a00;
  if (res[0]!=0) res[0][14]=a00;
  if (res[0]!=0) res[0][15]=a00;
  if (res[0]!=0) res[0][16]=a00;
  if (res[0]!=0) res[0][17]=a00;
  if (res[0]!=0) res[0][18]=a00;
  a15=(a01*a15);
  if (res[0]!=0) res[0][19]=a15;
  a14=(a01*a14);
  if (res[0]!=0) res[0][20]=a14;
  a13=(a01*a13);
  if (res[0]!=0) res[0][21]=a13;
  a12=(a01*a12);
  if (res[0]!=0) res[0][22]=a12;
  a11=(a01*a11);
  if (res[0]!=0) res[0][23]=a11;
  a01=(a01*a09);
  if (res[0]!=0) res[0][24]=a01;
  a01=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][25]=a01;
  a01=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][26]=a01;
  a01=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][27]=a01;
  a01=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][28]=a01;
  a01=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][29]=a01;
  a01=arg[1]? arg[1][18] : 0;
  if (res[0]!=0) res[0][30]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int UR5_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int UR5_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int UR5_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UR5_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int UR5_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UR5_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void UR5_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void UR5_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int UR5_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int UR5_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real UR5_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UR5_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UR5_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UR5_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UR5_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int UR5_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int UR5_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
