/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) UR5_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[63] = {59, 1, 0, 59, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58};
static const casadi_int casadi_s3[45] = {18, 12, 0, 3, 6, 9, 12, 15, 18, 20, 22, 24, 26, 28, 30, 0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 15, 4, 10, 16, 5, 11, 17, 0, 12, 1, 13, 2, 14, 3, 15, 4, 16, 5, 17};

/* UR5_dyn_disc_phi_fun_jac:(i0[12],i1[6],i2[59])->(o0[12],o1[18x12,30nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=5.0000000000000003e-02;
  a2=arg[0]? arg[0][6] : 0;
  a3=(a1*a2);
  a0=(a0+a3);
  a3=1.2500000000000002e-03;
  a4=arg[1]? arg[1][0] : 0;
  a5=(a3*a4);
  a0=(a0+a5);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a5=arg[0]? arg[0][7] : 0;
  a6=(a1*a5);
  a0=(a0+a6);
  a6=arg[1]? arg[1][1] : 0;
  a7=(a3*a6);
  a0=(a0+a7);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a7=arg[0]? arg[0][8] : 0;
  a8=(a1*a7);
  a0=(a0+a8);
  a8=arg[1]? arg[1][2] : 0;
  a9=(a3*a8);
  a0=(a0+a9);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a9=arg[0]? arg[0][9] : 0;
  a10=(a1*a9);
  a0=(a0+a10);
  a10=arg[1]? arg[1][3] : 0;
  a11=(a3*a10);
  a0=(a0+a11);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a11=arg[0]? arg[0][10] : 0;
  a12=(a1*a11);
  a0=(a0+a12);
  a12=arg[1]? arg[1][4] : 0;
  a13=(a3*a12);
  a0=(a0+a13);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a13=arg[0]? arg[0][11] : 0;
  a14=(a1*a13);
  a0=(a0+a14);
  a14=arg[1]? arg[1][5] : 0;
  a15=(a3*a14);
  a0=(a0+a15);
  if (res[0]!=0) res[0][5]=a0;
  a4=(a1*a4);
  a2=(a2+a4);
  if (res[0]!=0) res[0][6]=a2;
  a6=(a1*a6);
  a5=(a5+a6);
  if (res[0]!=0) res[0][7]=a5;
  a8=(a1*a8);
  a7=(a7+a8);
  if (res[0]!=0) res[0][8]=a7;
  a10=(a1*a10);
  a9=(a9+a10);
  if (res[0]!=0) res[0][9]=a9;
  a12=(a1*a12);
  a11=(a11+a12);
  if (res[0]!=0) res[0][10]=a11;
  a14=(a1*a14);
  a13=(a13+a14);
  if (res[0]!=0) res[0][11]=a13;
  if (res[1]!=0) res[1][0]=a3;
  a13=1.;
  if (res[1]!=0) res[1][1]=a13;
  if (res[1]!=0) res[1][2]=a1;
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a13;
  if (res[1]!=0) res[1][5]=a1;
  if (res[1]!=0) res[1][6]=a3;
  if (res[1]!=0) res[1][7]=a13;
  if (res[1]!=0) res[1][8]=a1;
  if (res[1]!=0) res[1][9]=a3;
  if (res[1]!=0) res[1][10]=a13;
  if (res[1]!=0) res[1][11]=a1;
  if (res[1]!=0) res[1][12]=a3;
  if (res[1]!=0) res[1][13]=a13;
  if (res[1]!=0) res[1][14]=a1;
  if (res[1]!=0) res[1][15]=a3;
  if (res[1]!=0) res[1][16]=a13;
  if (res[1]!=0) res[1][17]=a1;
  if (res[1]!=0) res[1][18]=a1;
  if (res[1]!=0) res[1][19]=a13;
  if (res[1]!=0) res[1][20]=a1;
  if (res[1]!=0) res[1][21]=a13;
  if (res[1]!=0) res[1][22]=a1;
  if (res[1]!=0) res[1][23]=a13;
  if (res[1]!=0) res[1][24]=a1;
  if (res[1]!=0) res[1][25]=a13;
  if (res[1]!=0) res[1][26]=a1;
  if (res[1]!=0) res[1][27]=a13;
  if (res[1]!=0) res[1][28]=a1;
  if (res[1]!=0) res[1][29]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int UR5_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int UR5_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int UR5_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UR5_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int UR5_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UR5_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void UR5_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void UR5_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int UR5_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int UR5_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real UR5_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UR5_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UR5_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UR5_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UR5_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int UR5_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
