/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) UR5_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s4[41] = {37, 1, 0, 37, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36};
static const casadi_int casadi_s5[105] = {30, 37, 0, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 18, 19, 20, 21, 22, 6, 18, 7, 19, 8, 20, 9, 21, 10, 22, 11, 23, 12, 24, 13, 25, 14, 26, 15, 27, 16, 28, 17, 29, 6, 18, 7, 19, 8, 20, 9, 21, 10, 22, 11, 23, 12, 24, 13, 25, 14, 26, 15, 27, 16, 28, 17, 29, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s6[3] = {37, 0, 0};

/* UR5_constr_h_fun_jac_uxt_zt:(i0[12],i1[18],i2[],i3[7])->(o0[37],o1[30x37,65nz],o2[37x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a8, a9;
  a0=3.2500000000000001e-02;
  a1=3.9224999999999999e-01;
  a2=arg[0]? arg[0][0] : 0;
  a3=cos(a2);
  a4=arg[0]? arg[0][1] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a7=arg[0]? arg[0][2] : 0;
  a8=cos(a7);
  a9=(a6*a8);
  a10=sin(a4);
  a11=(a3*a10);
  a12=sin(a7);
  a13=(a11*a12);
  a9=(a9-a13);
  a13=(a1*a9);
  a14=4.2499999999999999e-01;
  a15=(a14*a6);
  a16=-1.1970000000000000e-01;
  a17=sin(a2);
  a18=(a16*a17);
  a15=(a15-a18);
  a18=1.3585000000000000e-01;
  a19=(a18*a17);
  a15=(a15-a19);
  a13=(a13+a15);
  a15=9.2999999999999999e-02;
  a19=(a15*a17);
  a13=(a13-a19);
  a19=9.4649999999999998e-02;
  a20=cos(a7);
  a21=(a11*a20);
  a22=sin(a7);
  a23=(a6*a22);
  a21=(a21+a23);
  a23=arg[0]? arg[0][3] : 0;
  a24=cos(a23);
  a25=(a21*a24);
  a26=sin(a23);
  a27=(a9*a26);
  a25=(a25+a27);
  a25=(a19*a25);
  a13=(a13-a25);
  a25=4.1099999999999998e-02;
  a27=sin(a23);
  a28=(a21*a27);
  a29=cos(a23);
  a30=(a9*a29);
  a28=(a28-a30);
  a30=arg[0]? arg[0][4] : 0;
  a31=sin(a30);
  a32=(a28*a31);
  a33=cos(a30);
  a34=(a17*a33);
  a32=(a32+a34);
  a32=(a25*a32);
  a13=(a13-a32);
  a32=6.7900000000000002e-02;
  a34=(a32*a17);
  a13=(a13+a34);
  a34=casadi_sq(a13);
  a35=cos(a2);
  a36=(a35*a33);
  a37=sin(a2);
  a38=(a37*a10);
  a39=(a38*a20);
  a40=(a37*a5);
  a41=(a40*a22);
  a39=(a39+a41);
  a41=(a39*a27);
  a42=(a40*a8);
  a43=(a38*a12);
  a42=(a42-a43);
  a43=(a42*a29);
  a41=(a41-a43);
  a43=(a41*a31);
  a36=(a36-a43);
  a36=(a25*a36);
  a43=(a15*a35);
  a44=(a1*a42);
  a45=(a16*a35);
  a46=(a14*a40);
  a45=(a45+a46);
  a46=(a18*a35);
  a45=(a45+a46);
  a44=(a44+a45);
  a43=(a43+a44);
  a44=(a39*a24);
  a45=(a42*a26);
  a44=(a44+a45);
  a44=(a19*a44);
  a43=(a43-a44);
  a36=(a36+a43);
  a43=(a32*a35);
  a36=(a36-a43);
  a43=casadi_sq(a36);
  a34=(a34+a43);
  a43=sin(a4);
  a44=(a43*a22);
  a45=cos(a4);
  a46=(a45*a20);
  a44=(a44-a46);
  a46=(a44*a24);
  a47=(a45*a12);
  a48=(a43*a8);
  a47=(a47+a48);
  a48=(a47*a26);
  a46=(a46+a48);
  a46=(a19*a46);
  a48=8.9159000000000002e-02;
  a49=(a14*a43);
  a49=(a48-a49);
  a50=(a1*a47);
  a49=(a49-a50);
  a46=(a46+a49);
  a49=(a47*a29);
  a50=(a44*a27);
  a49=(a49-a50);
  a50=(a49*a31);
  a50=(a25*a50);
  a46=(a46-a50);
  a46=(a46-a48);
  a48=casadi_sq(a46);
  a34=(a34+a48);
  a0=(a0-a34);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][1] : 0;
  a0=(a2-a0);
  a34=arg[1]? arg[1][6] : 0;
  a48=(a0-a34);
  if (res[0]!=0) res[0][1]=a48;
  a48=arg[3]? arg[3][2] : 0;
  a48=(a4-a48);
  a50=arg[1]? arg[1][7] : 0;
  a51=(a48-a50);
  if (res[0]!=0) res[0][2]=a51;
  a51=arg[3]? arg[3][3] : 0;
  a51=(a7-a51);
  a52=arg[1]? arg[1][8] : 0;
  a53=(a51-a52);
  if (res[0]!=0) res[0][3]=a53;
  a53=arg[3]? arg[3][4] : 0;
  a53=(a23-a53);
  a54=arg[1]? arg[1][9] : 0;
  a55=(a53-a54);
  if (res[0]!=0) res[0][4]=a55;
  a55=arg[3]? arg[3][5] : 0;
  a55=(a30-a55);
  a56=arg[1]? arg[1][10] : 0;
  a57=(a55-a56);
  if (res[0]!=0) res[0][5]=a57;
  a57=arg[0]? arg[0][5] : 0;
  a58=arg[3]? arg[3][6] : 0;
  a57=(a57-a58);
  a58=arg[1]? arg[1][11] : 0;
  a59=(a57-a58);
  if (res[0]!=0) res[0][6]=a59;
  a59=arg[0]? arg[0][6] : 0;
  a60=arg[1]? arg[1][12] : 0;
  a61=(a59-a60);
  if (res[0]!=0) res[0][7]=a61;
  a61=arg[0]? arg[0][7] : 0;
  a62=arg[1]? arg[1][13] : 0;
  a63=(a61-a62);
  if (res[0]!=0) res[0][8]=a63;
  a63=arg[0]? arg[0][8] : 0;
  a64=arg[1]? arg[1][14] : 0;
  a65=(a63-a64);
  if (res[0]!=0) res[0][9]=a65;
  a65=arg[0]? arg[0][9] : 0;
  a66=arg[1]? arg[1][15] : 0;
  a67=(a65-a66);
  if (res[0]!=0) res[0][10]=a67;
  a67=arg[0]? arg[0][10] : 0;
  a68=arg[1]? arg[1][16] : 0;
  a69=(a67-a68);
  if (res[0]!=0) res[0][11]=a69;
  a69=arg[0]? arg[0][11] : 0;
  a70=arg[1]? arg[1][17] : 0;
  a71=(a69-a70);
  if (res[0]!=0) res[0][12]=a71;
  a0=(a0+a34);
  a0=(-a0);
  if (res[0]!=0) res[0][13]=a0;
  a48=(a48+a50);
  a48=(-a48);
  if (res[0]!=0) res[0][14]=a48;
  a51=(a51+a52);
  a51=(-a51);
  if (res[0]!=0) res[0][15]=a51;
  a53=(a53+a54);
  a53=(-a53);
  if (res[0]!=0) res[0][16]=a53;
  a55=(a55+a56);
  a55=(-a55);
  if (res[0]!=0) res[0][17]=a55;
  a57=(a57+a58);
  a57=(-a57);
  if (res[0]!=0) res[0][18]=a57;
  a59=(a59+a60);
  a59=(-a59);
  if (res[0]!=0) res[0][19]=a59;
  a61=(a61+a62);
  a61=(-a61);
  if (res[0]!=0) res[0][20]=a61;
  a63=(a63+a64);
  a63=(-a63);
  if (res[0]!=0) res[0][21]=a63;
  a65=(a65+a66);
  a65=(-a65);
  if (res[0]!=0) res[0][22]=a65;
  a67=(a67+a68);
  a67=(-a67);
  if (res[0]!=0) res[0][23]=a67;
  a69=(a69+a70);
  a69=(-a69);
  if (res[0]!=0) res[0][24]=a69;
  a34=(-a34);
  if (res[0]!=0) res[0][25]=a34;
  a50=(-a50);
  if (res[0]!=0) res[0][26]=a50;
  a52=(-a52);
  if (res[0]!=0) res[0][27]=a52;
  a54=(-a54);
  if (res[0]!=0) res[0][28]=a54;
  a56=(-a56);
  if (res[0]!=0) res[0][29]=a56;
  a58=(-a58);
  if (res[0]!=0) res[0][30]=a58;
  a60=(-a60);
  if (res[0]!=0) res[0][31]=a60;
  a62=(-a62);
  if (res[0]!=0) res[0][32]=a62;
  a64=(-a64);
  if (res[0]!=0) res[0][33]=a64;
  a66=(-a66);
  if (res[0]!=0) res[0][34]=a66;
  a68=(-a68);
  if (res[0]!=0) res[0][35]=a68;
  a70=(-a70);
  if (res[0]!=0) res[0][36]=a70;
  a13=(a13+a13);
  a70=sin(a2);
  a68=(a10*a70);
  a66=(a12*a68);
  a70=(a5*a70);
  a64=(a8*a70);
  a66=(a66-a64);
  a64=(a1*a66);
  a62=(a14*a70);
  a60=cos(a2);
  a58=(a16*a60);
  a62=(a62+a58);
  a58=(a18*a60);
  a62=(a62+a58);
  a64=(a64-a62);
  a62=(a15*a60);
  a64=(a64-a62);
  a62=(a26*a66);
  a68=(a20*a68);
  a70=(a22*a70);
  a68=(a68+a70);
  a70=(a24*a68);
  a62=(a62-a70);
  a62=(a19*a62);
  a64=(a64-a62);
  a62=(a33*a60);
  a68=(a27*a68);
  a66=(a29*a66);
  a68=(a68+a66);
  a68=(a31*a68);
  a62=(a62-a68);
  a62=(a25*a62);
  a64=(a64-a62);
  a60=(a32*a60);
  a64=(a64+a60);
  a64=(a13*a64);
  a36=(a36+a36);
  a60=cos(a2);
  a5=(a5*a60);
  a62=(a8*a5);
  a10=(a10*a60);
  a60=(a12*a10);
  a62=(a62-a60);
  a60=(a1*a62);
  a68=(a14*a5);
  a2=sin(a2);
  a16=(a16*a2);
  a68=(a68-a16);
  a18=(a18*a2);
  a68=(a68-a18);
  a60=(a60+a68);
  a15=(a15*a2);
  a60=(a60-a15);
  a10=(a20*a10);
  a5=(a22*a5);
  a10=(a10+a5);
  a5=(a24*a10);
  a15=(a26*a62);
  a5=(a5+a15);
  a5=(a19*a5);
  a60=(a60-a5);
  a33=(a33*a2);
  a10=(a27*a10);
  a62=(a29*a62);
  a10=(a10-a62);
  a10=(a31*a10);
  a33=(a33+a10);
  a33=(a25*a33);
  a60=(a60-a33);
  a32=(a32*a2);
  a60=(a60+a32);
  a60=(a36*a60);
  a64=(a64+a60);
  a64=(-a64);
  if (res[1]!=0) res[1][0]=a64;
  a46=(a46+a46);
  a64=cos(a4);
  a60=(a22*a64);
  a32=sin(a4);
  a2=(a20*a32);
  a60=(a60+a2);
  a2=(a24*a60);
  a33=(a8*a64);
  a32=(a12*a32);
  a33=(a33-a32);
  a32=(a26*a33);
  a2=(a2+a32);
  a2=(a19*a2);
  a64=(a14*a64);
  a32=(a1*a33);
  a64=(a64+a32);
  a2=(a2-a64);
  a33=(a29*a33);
  a60=(a27*a60);
  a33=(a33-a60);
  a33=(a31*a33);
  a33=(a25*a33);
  a2=(a2-a33);
  a2=(a46*a2);
  a33=sin(a4);
  a60=(a3*a33);
  a64=(a8*a60);
  a4=cos(a4);
  a3=(a3*a4);
  a32=(a12*a3);
  a64=(a64+a32);
  a32=(a1*a64);
  a10=(a14*a60);
  a32=(a32+a10);
  a3=(a20*a3);
  a60=(a22*a60);
  a3=(a3-a60);
  a60=(a24*a3);
  a10=(a26*a64);
  a60=(a60-a10);
  a60=(a19*a60);
  a32=(a32+a60);
  a3=(a27*a3);
  a64=(a29*a64);
  a3=(a3+a64);
  a3=(a31*a3);
  a3=(a25*a3);
  a32=(a32+a3);
  a32=(a13*a32);
  a4=(a37*a4);
  a20=(a20*a4);
  a37=(a37*a33);
  a22=(a22*a37);
  a20=(a20-a22);
  a22=(a27*a20);
  a8=(a8*a37);
  a12=(a12*a4);
  a8=(a8+a12);
  a12=(a29*a8);
  a22=(a22+a12);
  a22=(a31*a22);
  a22=(a25*a22);
  a12=(a1*a8);
  a14=(a14*a37);
  a12=(a12+a14);
  a20=(a24*a20);
  a8=(a26*a8);
  a20=(a20-a8);
  a20=(a19*a20);
  a12=(a12+a20);
  a22=(a22+a12);
  a22=(a36*a22);
  a32=(a32+a22);
  a2=(a2-a32);
  a2=(-a2);
  if (res[1]!=0) res[1][1]=a2;
  a2=cos(a7);
  a32=(a43*a2);
  a22=sin(a7);
  a12=(a45*a22);
  a32=(a32+a12);
  a12=(a24*a32);
  a20=cos(a7);
  a45=(a45*a20);
  a7=sin(a7);
  a43=(a43*a7);
  a45=(a45-a43);
  a43=(a26*a45);
  a12=(a12+a43);
  a12=(a19*a12);
  a43=(a1*a45);
  a12=(a12-a43);
  a45=(a29*a45);
  a32=(a27*a32);
  a45=(a45-a32);
  a45=(a31*a45);
  a45=(a25*a45);
  a12=(a12-a45);
  a12=(a46*a12);
  a45=(a6*a7);
  a32=(a11*a20);
  a45=(a45+a32);
  a32=(a1*a45);
  a6=(a6*a2);
  a11=(a11*a22);
  a6=(a6-a11);
  a11=(a24*a6);
  a43=(a26*a45);
  a11=(a11-a43);
  a11=(a19*a11);
  a32=(a32+a11);
  a6=(a27*a6);
  a45=(a29*a45);
  a6=(a6+a45);
  a6=(a31*a6);
  a6=(a25*a6);
  a32=(a32+a6);
  a32=(a13*a32);
  a2=(a40*a2);
  a22=(a38*a22);
  a2=(a2-a22);
  a27=(a27*a2);
  a40=(a40*a7);
  a38=(a38*a20);
  a40=(a40+a38);
  a29=(a29*a40);
  a27=(a27+a29);
  a27=(a31*a27);
  a27=(a25*a27);
  a1=(a1*a40);
  a24=(a24*a2);
  a26=(a26*a40);
  a24=(a24-a26);
  a24=(a19*a24);
  a1=(a1+a24);
  a27=(a27+a1);
  a27=(a36*a27);
  a32=(a32+a27);
  a12=(a12-a32);
  a12=(-a12);
  if (res[1]!=0) res[1][2]=a12;
  a12=cos(a23);
  a32=(a47*a12);
  a27=sin(a23);
  a1=(a44*a27);
  a32=(a32-a1);
  a32=(a19*a32);
  a1=sin(a23);
  a47=(a47*a1);
  a23=cos(a23);
  a44=(a44*a23);
  a47=(a47+a44);
  a47=(a31*a47);
  a47=(a25*a47);
  a32=(a32+a47);
  a32=(a46*a32);
  a47=(a9*a12);
  a44=(a21*a27);
  a47=(a47-a44);
  a47=(a19*a47);
  a21=(a21*a23);
  a9=(a9*a1);
  a21=(a21+a9);
  a21=(a31*a21);
  a21=(a25*a21);
  a47=(a47+a21);
  a47=(a13*a47);
  a23=(a39*a23);
  a1=(a42*a1);
  a23=(a23+a1);
  a31=(a31*a23);
  a31=(a25*a31);
  a42=(a42*a12);
  a39=(a39*a27);
  a42=(a42-a39);
  a19=(a19*a42);
  a31=(a31+a19);
  a31=(a36*a31);
  a47=(a47+a31);
  a32=(a32-a47);
  a32=(-a32);
  if (res[1]!=0) res[1][3]=a32;
  a32=cos(a30);
  a28=(a28*a32);
  a30=sin(a30);
  a17=(a17*a30);
  a28=(a28-a17);
  a28=(a25*a28);
  a13=(a13*a28);
  a35=(a35*a30);
  a41=(a41*a32);
  a35=(a35+a41);
  a35=(a25*a35);
  a36=(a36*a35);
  a13=(a13+a36);
  a49=(a49*a32);
  a25=(a25*a49);
  a46=(a46*a25);
  a13=(a13+a46);
  if (res[1]!=0) res[1][4]=a13;
  a13=-1.;
  if (res[1]!=0) res[1][5]=a13;
  a46=1.;
  if (res[1]!=0) res[1][6]=a46;
  if (res[1]!=0) res[1][7]=a13;
  if (res[1]!=0) res[1][8]=a46;
  if (res[1]!=0) res[1][9]=a13;
  if (res[1]!=0) res[1][10]=a46;
  if (res[1]!=0) res[1][11]=a13;
  if (res[1]!=0) res[1][12]=a46;
  if (res[1]!=0) res[1][13]=a13;
  if (res[1]!=0) res[1][14]=a46;
  if (res[1]!=0) res[1][15]=a13;
  if (res[1]!=0) res[1][16]=a46;
  if (res[1]!=0) res[1][17]=a13;
  if (res[1]!=0) res[1][18]=a46;
  if (res[1]!=0) res[1][19]=a13;
  if (res[1]!=0) res[1][20]=a46;
  if (res[1]!=0) res[1][21]=a13;
  if (res[1]!=0) res[1][22]=a46;
  if (res[1]!=0) res[1][23]=a13;
  if (res[1]!=0) res[1][24]=a46;
  if (res[1]!=0) res[1][25]=a13;
  if (res[1]!=0) res[1][26]=a46;
  if (res[1]!=0) res[1][27]=a13;
  if (res[1]!=0) res[1][28]=a46;
  if (res[1]!=0) res[1][29]=a13;
  if (res[1]!=0) res[1][30]=a13;
  if (res[1]!=0) res[1][31]=a13;
  if (res[1]!=0) res[1][32]=a13;
  if (res[1]!=0) res[1][33]=a13;
  if (res[1]!=0) res[1][34]=a13;
  if (res[1]!=0) res[1][35]=a13;
  if (res[1]!=0) res[1][36]=a13;
  if (res[1]!=0) res[1][37]=a13;
  if (res[1]!=0) res[1][38]=a13;
  if (res[1]!=0) res[1][39]=a13;
  if (res[1]!=0) res[1][40]=a13;
  if (res[1]!=0) res[1][41]=a13;
  if (res[1]!=0) res[1][42]=a13;
  if (res[1]!=0) res[1][43]=a13;
  if (res[1]!=0) res[1][44]=a13;
  if (res[1]!=0) res[1][45]=a13;
  if (res[1]!=0) res[1][46]=a13;
  if (res[1]!=0) res[1][47]=a13;
  if (res[1]!=0) res[1][48]=a13;
  if (res[1]!=0) res[1][49]=a13;
  if (res[1]!=0) res[1][50]=a13;
  if (res[1]!=0) res[1][51]=a13;
  if (res[1]!=0) res[1][52]=a13;
  if (res[1]!=0) res[1][53]=a13;
  if (res[1]!=0) res[1][54]=a13;
  if (res[1]!=0) res[1][55]=a13;
  if (res[1]!=0) res[1][56]=a13;
  if (res[1]!=0) res[1][57]=a13;
  if (res[1]!=0) res[1][58]=a13;
  if (res[1]!=0) res[1][59]=a13;
  if (res[1]!=0) res[1][60]=a13;
  if (res[1]!=0) res[1][61]=a13;
  if (res[1]!=0) res[1][62]=a13;
  if (res[1]!=0) res[1][63]=a13;
  if (res[1]!=0) res[1][64]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int UR5_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int UR5_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int UR5_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UR5_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int UR5_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UR5_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void UR5_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void UR5_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int UR5_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int UR5_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real UR5_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UR5_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UR5_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UR5_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UR5_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int UR5_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
